# FIXME: how to specify build command in this file read by CF deployment builders?
# build command: make build
# root directory: /

name = "rpg"
pages_build_output_dir = "public"

[vars]
HUGO_VERSION = "0.140.2+extended"
