# FIXME: is this file read by CF deployment builders?
# build command: hugo --minify -b $CF_PAGES_URL
# output directory: public/
# root directory: /

name = "rpg"
pages_build_output_dir = "public"

[vars]
HUGO_VERSION = "0.91.0"

[env.preview.vars]
HUGO_VERSION = "0.91.0"
