# FIXME: how to specify build command in this file read by CF deployment builders?
# build command: hugo --minify -b $CF_PAGES_URL
# root directory: /

name = "rpg"
pages_build_output_dir = "public"

[vars]
HUGO_VERSION = "0.134.2+extended"