name: new post

on: 
  workflow_dispatch:
    inputs:
      postName:
        description: 'Title'
        required: true
        default: 'void'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
